name: "Castor Build Action"
description: "Automate building Zoo Tycoon 2 mods with Castor"
branding:
  icon: archive
  color: red
author: "ZtModArchive"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v1
    - run: dotnet tool install --global Castor --version 4.1.0
      shell: bash
    - run: castor build
      shell: bash
